### PR TITLE
Add middleware to prevent clickjacking

### PR DESCRIPTION
**Pull request by xuxinx**

### CODE REVIEW

**Review by bodhi — COMMENTED** [review]
@xuxinx what is the default behaviour if no options are set? It looks to me like it will be:

```
Content-Security-Policy: frame-ancestors
```

which appears to be invalid according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors), assuming that `<source>` cannot be an empty list:

> *One or more* sources can be set for the `frame-ancestors` policy

[emphasis added]

I'd recommend the default be the strongest option, which I guess would be:

```
Content-Security-Policy: frame-ancestors 'none'
X-Frame-Options: DENY
```

(And `X-Frame-Options` is the legacy header)

**Comment by xuxinx** [comment]
> what is the default behaviour if no options are set?

if no options are set, it just returns the IdMiddleware https://github.com/theplant/appkit/blob/add-middleware-to-prevent-clickjacking/service/middleware.go#L337-L340

> I'd recommend the default be the strongest option, which I guess would be:
> Content-Security-Policy: frame-ancestors 'none'
> X-Frame-Options: DENY

If we need to provide a default option, I think
```
Content-Security-Policy: frame-ancestors 'self'
X-Frame-Options: SAMEORIGIN
```
is better which also avoids clickjacking from other origins and does not affect the iframe usage on the same origin.

**Comment by xuxinx** [comment]
@bodhi :point_up: any more comments/reviews?

**Comment by bodhi** [comment]
@xuxinx sorry for the delay.

> If we need to provide a default option, I think [`self/SAMEORIGIN`] is better which also avoids clickjacking from other origins and does not affect the iframe usage on the same origin.

Please make the default be *the most secure option*. Most projects do not need to embed themselves in a frame, and the ones that do can customise the configuration.

**Review by bodhi — APPROVED** [review]
Looks Good @xuxinx thanks! Sorry for the delay.

**Pull request merged**
