### PR TITLE
Source InfluxDB credentials via Vault

### PR DESCRIPTION
**Pull request by bodhi**

### CODE REVIEW

**Comment by bodhi** [comment]
> The build failed on Semaphore

```
# github.com/hashicorp/vault/vendor/github.com/hashicorp/go-retryablehttp
../../hashicorp/vault/vendor/github.com/hashicorp/go-retryablehttp/client.go:447:17: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
...
```

`hashicorp/go-retryablehttp` [made a change](https://github.com/hashicorp/go-retryablehttp/pull/57/files#r318415817) that is not compatible with Go v1.11, but Semaphore doesn't support Go v1.12 yet 😭.

**Comment by idealhack** [comment]
> Semaphore doesn't support Go v1.12 yet 😭

I know which project to on-board on prow next now :trollface:

**Comment by bodhi** [comment]
I think I can use modules to lock the tests to an earlier version that works on v1.11...

**Comment by bodhi** [comment]
I'm not going to fix the failing build in this PR.

**Pull request merged**
