### PR TITLE
Monitor batch write

### PR DESCRIPTION
**Pull request by lifenod**
solve https://github.com/theplant/appkit/issues/13

### CODE REVIEW

**Comment by lifenod** [comment]
> We need to find a way to push the data in the queue before the go routine being cancelling, currently, the data in the queue will lost once the go routine is cancelled.

May we do some cleaning work when we receive theSIGTERM signal, deed to do some research.

**Comment by lifenod** [comment]
> A simple way, wait > 1m (or set a smaller batch interval) when to close the pod.

@qi-zhou Please confirm if K8s has this waiting time.

**Comment by bodhi** [comment]
Oops. Review submitted early by accident, sorry!

> Here's a refernece

What I was going to say was: Here's an (older) reference that says 5-10k events per request is a good amount: https://community.influxdata.com/t/what-is-the-highest-performance-method-of-getting-data-in-out-of-influxdb/464

**Comment by lifenod** [comment]
move to https://github.com/theplant/appkit/pull/25

**Pull request closed without merging**
